name: create-png
run-name: Creating PNG from SVG

permissions: 
  contents: write

on:
  pull_request:
    types:
      [opened, reopened, synchronize]
    paths: 
      - "FAQ.svg"
      
jobs:
  send-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Send Preview'
        run: |
          gh pr comment $PRNUM --body-file FAQ.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
